In [87]:
import numpy as np
import torch
import ankh
import pandas as pd

In [ ]:
#model, tokenizer = ankh.load_large_model()
#model.eval()

In [88]:
model, tokenizer = ankh.load_base_model()
model.eval()

T5EncoderModel(
  (shared): Embedding(144, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(144, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(64, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=3072, bias=False)
              (wi_1): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_featu

In [3]:
df = pd.read_csv("training.csv")
df_1 = df[df['Label'] == 1].sample(frac=0.01, random_state=1)
df_0 = df[df['Label'] == 0].sample(frac=0.01, random_state=1)

df_new = pd.concat([df_1, df_0], ignore_index=True)

In [200]:
protein_sequences = df['Sequence'][0:3].tolist()
embeddings = []
for protein_seq in protein_sequences:
    temp = [list(seq) for seq in protein_seq]
    outputs = tokenizer.batch_encode_plus(temp, 
                                          add_special_tokens=True, 
                                          padding=True, 
                                          is_split_into_words=True, 
                                          return_tensors="pt")
    with torch.no_grad():
        embedding = model(input_ids=outputs['input_ids'], attention_mask=outputs['attention_mask'])[0]
        embeddings_1 = embedding[:,1]
        embeddings_1_average = []
        for n in range(len(embeddings_0[0])):
            embeddings_1_average.append(np.mean(embeddings_1[:,n].tolist()))
        print(len(embeddings_1_average))

768
768
768


In [208]:
df = pd.DataFrame(embeddings_1_average)
df.T.to_csv('temp.csv', index=False)

In [184]:
embeddings[0][:,1]

tensor([[-0.0263, -0.0115,  0.0016,  ...,  0.0363,  0.0042, -0.0050],
        [-0.0139,  0.0100,  0.0177,  ...,  0.0241, -0.0303, -0.0066],
        [-0.0169, -0.0072,  0.0018,  ...,  0.0184, -0.0124, -0.0027],
        ...,
        [-0.0133,  0.0072,  0.0143,  ...,  0.0230, -0.0211, -0.0002],
        [-0.0065, -0.0057, -0.0058,  ...,  0.0235, -0.0086, -0.0093],
        [-0.0302,  0.0054,  0.0114,  ...,  0.0272, -0.0167, -0.0192]])

In [183]:
embeddings[0]

tensor([[[ 0.0340,  0.0520, -0.0549,  ..., -0.0168,  0.0137, -0.0351],
         [-0.0263, -0.0115,  0.0016,  ...,  0.0363,  0.0042, -0.0050]],

        [[-0.0133,  0.0369, -0.0026,  ..., -0.0295,  0.0094, -0.0352],
         [-0.0139,  0.0100,  0.0177,  ...,  0.0241, -0.0303, -0.0066]],

        [[ 0.0211,  0.0553,  0.0602,  ..., -0.0562, -0.0080, -0.0102],
         [-0.0169, -0.0072,  0.0018,  ...,  0.0184, -0.0124, -0.0027]],

        ...,

        [[ 0.0164,  0.0040, -0.0266,  ..., -0.0109,  0.0162,  0.0057],
         [-0.0133,  0.0072,  0.0143,  ...,  0.0230, -0.0211, -0.0002]],

        [[ 0.0074, -0.0079,  0.0231,  ..., -0.0129, -0.0115, -0.0231],
         [-0.0065, -0.0057, -0.0058,  ...,  0.0235, -0.0086, -0.0093]],

        [[-0.0221,  0.0514,  0.0105,  ..., -0.0425,  0.0132,  0.0022],
         [-0.0302,  0.0054,  0.0114,  ...,  0.0272, -0.0167, -0.0192]]])

In [164]:
len(embeddings[0][:,1])

867

In [155]:
len(embeddings[0])

867

In [187]:
len(embeddings_1_average)

768

In [7]:
def dimention_reduction(embeddings_def):
    dimention_reduction_result = []
    for i in range(len(embeddings_def[0])):
        dimention_reduction_result.append(np.mean(embeddings_def[:,i].tolist()))
    return dimention_reduction_result

In [8]:
for n in range(len(embeddings[0])):
    print(n)
    if n == 0:
        feature_temp = {
            '0': dimention_reduction(embeddings[0][n])
        }
        feature = pd.DataFrame.from_dict(feature_temp, orient='index')
    else:
        feature.loc[n] = dimention_reduction(embeddings[0][n])
#feature.to_csv('feature.csv', index=False)

0
1
2


In [69]:
df = pd.read_csv("training.csv")
protein_sequences1 = df['Sequence'].tolist()[0:3]
protein_sequences1 = [list(seq) for seq in protein_sequences1]
embeddings1 = []
for i in range(len(protein_sequences1)):
    print(i)
    temp = []
    temp.append(protein_sequences1[i])
    outputs1 = tokenizer.batch_encode_plus(temp, 
                                          add_special_tokens=True, 
                                          padding=True, 
                                          is_split_into_words=True, 
                                          return_tensors="pt")
    with torch.no_grad():
        embeddings1.append(model(input_ids=outputs1['input_ids'], attention_mask=outputs1['attention_mask'])[0][0])

0
1
2


In [70]:
embeddings1

[tensor([[ 0.0057, -0.0092, -0.0049,  ..., -0.0095, -0.0169, -0.0296],
         [-0.0401, -0.0215, -0.0087,  ..., -0.0215,  0.0336, -0.0066],
         [ 0.0176,  0.0188,  0.0912,  ..., -0.0337,  0.0125, -0.0074],
         ...,
         [-0.0187,  0.0086,  0.0147,  ...,  0.0365, -0.0331, -0.0453],
         [-0.0168,  0.0495, -0.0131,  ..., -0.0111,  0.0366, -0.0308],
         [-0.0302, -0.0090,  0.0018,  ...,  0.0329, -0.0043, -0.0132]]),
 tensor([[ 0.0113, -0.0059, -0.0041,  ...,  0.0018, -0.0152, -0.0424],
         [-0.0005, -0.0089,  0.0104,  ...,  0.0411,  0.0426, -0.0462],
         [-0.0329,  0.0356, -0.0119,  ..., -0.0101,  0.0205, -0.0183],
         ...,
         [-0.0482,  0.0041,  0.0047,  ...,  0.0146, -0.0225, -0.0258],
         [-0.0267,  0.0399,  0.0172,  ...,  0.0292, -0.0051, -0.0552],
         [-0.0315, -0.0112,  0.0046,  ...,  0.0332, -0.0093, -0.0109]]),
 tensor([[ 0.0132, -0.0161, -0.0116,  ..., -0.0338, -0.0224,  0.0028],
         [-0.0821,  0.0020, -0.0945,  ..., -0

In [71]:
df = pd.read_csv("training.csv")
protein_sequences = df['Sequence'].tolist()[0:3]
protein_sequences = [list(seq) for seq in protein_sequences]

outputs = tokenizer.batch_encode_plus(protein_sequences, 
                                    add_special_tokens=True, 
                                    padding=True, 
                                    is_split_into_words=True, 
                                    return_tensors="pt")
with torch.no_grad():
    embeddings = model(input_ids=outputs['input_ids'], attention_mask=outputs['attention_mask'])
    

In [74]:
embeddings[0][0]

tensor([[ 0.0057, -0.0092, -0.0049,  ..., -0.0095, -0.0169, -0.0296],
        [-0.0401, -0.0215, -0.0087,  ..., -0.0215,  0.0336, -0.0066],
        [ 0.0176,  0.0188,  0.0912,  ..., -0.0337,  0.0125, -0.0074],
        ...,
        [-0.0187,  0.0086,  0.0147,  ...,  0.0365, -0.0331, -0.0453],
        [-0.0168,  0.0495, -0.0131,  ..., -0.0111,  0.0366, -0.0308],
        [-0.0302, -0.0090,  0.0018,  ...,  0.0329, -0.0043, -0.0132]])